# Generated by Django 4.2.27 on 2026-01-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to='dogs.dog')),
                ('to_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to='dogs.dog')),
            ],
        ),
    ]
