# Generated by Django 4.2.27 on 2026-02-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_gender'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_given', to='dogs.dog')),
                ('to_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_received', to='dogs.dog')),
            ],
        ),
    ]
