# Generated by Django 4.2.27 on 2026-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_dislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dislike',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(
                fields=('from_dog', 'to_dog'),
                name='unique_connection',
            ),
        ),
        migrations.AddConstraint(
            model_name='dislike',
            constraint=models.UniqueConstraint(
                fields=('from_dog', 'to_dog'),
                name='unique_dislike',
            ),
        ),
    ]
