# Generated by Django 4.2.27 on 2026-03-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_fix_profile_photo_null'),
        ('connections', '0003_alter_connection_options_alter_dislike_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameModel(
                    old_name='Connection',
                    new_name='Like',
                ),
                migrations.AlterModelTable(
                    name='like',
                    table='connections_connection',
                ),
            ],
        ),
    ]
