# Generated by Django 4.2.27 on 2026-01-04 17:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile picture'),
        ),
    ]
