# Generated by Django 4.2.27 on 2026-01-21 18:59

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_remove_ownerprofile_bio_remove_ownerprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='interests',
            field=models.CharField(blank=True, help_text='Comma-separated interests', max_length=255),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile photo'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
