# Generated by Django 4.2.27 on 2026-01-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_ownerprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
