# Generated by Django 4.2.27 on 2026-02-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_ownerprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='interests',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
