# Generated by Django 4.2.27 on 2026-03-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_ownerprofile_about_me_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerprofile',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Owner Profile',
                'verbose_name_plural': 'Owner Profiles'
            },
        ),
    ]
