# Generated by Django 4.2.27 on 2026-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_ownerprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
