# Generated by Django 4.2.27 on 2026-01-04 17:30

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_remove_ownerprofile_bio_remove_ownerprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('energy_level', models.CharField(choices=[('couch_potato', '🛋️ Couch potato'), ('chill', '😌 Chill vibes'), ('playful', '🎾 Playful'), ('energetic', '⚡ Energetic'), ('zoomies', '🚀 Full zoomies')], max_length=12)),
                ('description', models.TextField(blank=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='dog picture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='profiles.ownerprofile')),
            ],
        ),
    ]
