# Generated by Django 4.2.27 on 2026-01-21 19:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='dog',
            name='about_me',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dog',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='dog profile photo'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('couch_potato', '🥔 Couch potato'), ('chill', '😌 Chill vibes'), ('playful', '🎾 Playful'), ('energetic', '⚡️ Energetic'), ('zoomies', '🚀 Full zoomies')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10),
        ),
    ]
