# Generated by Django 4.2.27 on 2026-01-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_remove_dog_description_remove_dog_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='about_me',
            field=models.TextField(blank=True, help_text="Tell us about your dog's personality", max_length=500),
        ),
    ]
