# Generated by Django 4.2.27 on 2026-02-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='about_me',
            field=models.TextField(blank=True, help_text="Tell us about your dog's personality", max_length=150),
        ),
    ]
