# Generated by Django 4.2.27 on 2026-02-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_alter_dog_about_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
            },
        ),
    ]
