# Generated by Django 4.2.27 on 2026-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_alter_dog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
