# Generated by Django 4.2.27 on 2026-02-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0005_dog_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='dogs.dog')),
                ('sender_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='dogs.dog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
